name: Dockerfile CI

on:
  push:
    paths:
      - 'Uebung02/**'
      - '.github/workflows/dockerfile.yml'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # will push to docker repository
    - name: Build and push to public repository
      uses: docker/build-push-action@v3
      with:
        run: cd 
        context: .
        file: "./Uebung02/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/democalc_public:latest